language: java
sudo: false
install:
- wget http://services.gradle.org/distributions/gradle-4.5.1-bin.zip
- unzip -qq gradle-4.5.1-bin.zip
- GRADLE_HOME=$PWD/gradle-4.5.1
- export PATH=$GRADLE_HOME/bin:$PATH
jdk:
- oraclejdk8
- oraclejdk9
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
addons:
  sonarcloud:
    organization: rafalkrupinski-github
    token:
      secure: EBOAKh48N8I2tj1NCU0L4IJSmiPWG0pVXScNn1owv+weMzKW6iCI6tBHZItYQ6Cz1+/QZWwkuWfjjg/5d6/g50SpTLxhEpruV0BTm+03aPH0FVv4hI02AHoH6459vbqVDOJCdIIONCaCNQClLy2vzD0m2aeXXgcdu4FBlHNoysXZ6UPG2E/gy0jPjXdxYp8KvgxglsLafs153wzwlPJ6/ms2il1AGYyfZraMHu7fycjUbBK9YvoTRcvVAyBfDuEEXxjQ8sQ84XbsbCysY2nL+qGsjDfqcLe/C1T14Ophis2E0xeMEZKJOywLs1qDSdMDi/kZ7+EUhhBiim9AP/NFnm4fBWjzzH2YziUKzY4L7oDbjUd5Ogjl7fN0/HVp8Amc9catX7BHsv88zrvF5jbS2SXHrj79p0wpBD6VD91MtecfLpLYDKyd0YEx0vb87gTRx344YkU9lARm1ssZCo5kdA1mNtIi/JxSlD19lt9wKh0AohvQ9DOrRSkjUXBDx6X7mlTlqc14hJiioQgrnkhX6DZxWu7qIqDTXU5bbYJfrdLtarOhxzVBkeW9L3yGMqcrYJIAk/gcYGjLqH4EEn7o0iUenIBLRx5//s1AXGjzwbRkOOSPeMuE/IgGWzkKeEeJaL7lR0A2SsxsPAZtGoQjOwPA+FqSZ/fUSAA6ncQ91sg=
    branches:
    - .*
script:
- gradle assemble
- gradle sonarqube
notifications:
  email:
    on_success: change
    on_failure: change
