language: java

sudo: false

jdk:
  - oraclejdk8
  - oraclejdk9

install:
  # Download desired version of Gradle
  - wget http://services.gradle.org/distributions/gradle-4.5.1-bin.zip
  - unzip -qq gradle-4.5.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-4.5.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  # just to test gradle version, against our provided one
  - gradle -v

#Gradle
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
